//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aerolineaEntities : DbContext
    {
        public aerolineaEntities()
            : base("name=aerolineaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aeropuertos> aeropuertos { get; set; }
        public virtual DbSet<aviones> aviones { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<reservaciones> reservaciones { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<vuelos> vuelos { get; set; }
    }
}
