//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class aeropuertos
    {
        public aeropuertos()
        {
            this.vuelos = new HashSet<vuelos>();
            this.vuelos1 = new HashSet<vuelos>();
        }
    
        public int idaeropuerto { get; set; }
        public string aeropuerto { get; set; }
        public int idpais { get; set; }
        public string ciudad { get; set; }
    
        public virtual paises paises { get; set; }
        public virtual ICollection<vuelos> vuelos { get; set; }
        public virtual ICollection<vuelos> vuelos1 { get; set; }
    }
}
