//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class paises
    {
        public paises()
        {
            this.aeropuertos = new HashSet<aeropuertos>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int idpais { get; set; }
        public string pais { get; set; }
    
        public virtual ICollection<aeropuertos> aeropuertos { get; set; }
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
