//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservaciones
    {
        public int idreservacion { get; set; }
        public string idusuario { get; set; }
        public int idvuelo { get; set; }
        public int nboletos { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual vuelos vuelos { get; set; }
    }
}
