//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuelos
    {
        public vuelos()
        {
            this.reservaciones = new HashSet<reservaciones>();
        }
    
        public int idvuelo { get; set; }
        public int idorigen { get; set; }
        public int iddestino { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<bool> estado { get; set; }
        public int idavion { get; set; }
    
        public virtual aeropuertos aeropuertos { get; set; }
        public virtual aeropuertos aeropuertos1 { get; set; }
        public virtual aviones aviones { get; set; }
        public virtual ICollection<reservaciones> reservaciones { get; set; }
    }
}
